ROOT_DIR := $(shell git rev-parse --show-toplevel)

SW_DIR 		:= $(ROOT_DIR)/sw
BIN_DIR		:= $(SW_DIR)/bin
OBJ_DIR 	:= $(BIN_DIR)/obj
LIB_DIR 	:= $(BIN_DIR)/lib
INC_DIR 	:= $(BIN_DIR)/include

PROJ_NAME	:= Utils Framework

SELF_CC		:= gcc
SELF_CXX	:= g++
SELF_AR		:= ar
SELF_RMV	:= rm -rf
SELF_CPY	:= cp -rf

SELF_LDFLAGS	:= -fPIC
SELF_CFLAGS	:= -c -g -Wall -Werror -Wextra
SELF_ARFLAGS	:= -rcs
SELF_SOFLAGS	:= -shared

# SDKSYSROOT is an env variable which should be exported by doing "source SDK-***/sysroot/env.sh
# which is automatically done by running atbuild-sdk.sh"
SDK_SYSROOT_DIR		:= $(SDKSYSROOT)
SDK_USR_DIR		:= $(SDK_SYSROOT_DIR)/usr
SDK_LIB_DIR		:= $(SDK_USR_DIR)/lib
SDK_INC_DIR		:= $(SDK_USR_DIR)/include