UF_CC		:= gcc
UF_AR		:= ar
UF_RMV		:= rm -rf
UF_CPY		:= cp -rf

UF_LDFLAGS	:= -fPIC
UF_CFLAGS	:= -c -g -Wall -Werror -Wextra
UF_ARFLAGS	:= -rcs
UF_SOFLAGS	:= -shared

PROJ_NAME	:= Utils Framework

SW_DIR 		:= $(ROOT_DIR)/sw
BIN_DIR		:= $(SW_DIR)/bin
OBJ_DIR 	:= $(BIN_DIR)/obj
LIB_DIR 	:= $(BIN_DIR)/lib
INC_DIR 	:= $(BIN_DIR)/include